### ISSUE TITLE
Provide a section about taxation

### ISSUE THREAD

**Issue by giampaolo** [lukasz-madon/awesome-remote-job#249]
It is a very complicate subject especially if you don't spend 183+ days in the same country. As such it would be good to have guidelines on where and how to pay taxes.

**Comment by lukasz-madon** [comment]
Great idea! PR is more than welcome.

**Comment by RichardLitt** [comment]
I think this is a bit out of scope for this list. As no one has done it, I think we should close this for now. It also potentially opens us up to liability, and, speaking as a remote worker for the past 7~ years - this issue is huge, and no list could possibly help navigate complicated tax structures between different countries, even cursorily. 

Thank you for the suggestion, however, @giampaolo.
