### ISSUE TITLE
Distinguish between contractor and full-time jobs

### ISSUE THREAD

**Issue by danse** [lukasz-madon/awesome-remote-job#252]
I find that job search can be deeply different, depending on the job being full or part time. Most sites for remote jobs just assume that one is going to look for a full time position. If i am looking for a remote job as a contractor on Angelist, for example, it will be easier for me to get relevant results selecting "contractor" first, and then checking for "remote ok", rather than the other way around.

Did you have a similar experience? Do you think that it makes sense to split the job section between "contractor" and "full time"?

**Comment by nikiyostudio** [comment]
Well for me, it indeed make sense. I'm a full-time freelance designer so currently most of my projects are come from internet, so obviously work in remote type. Usually I seeking job will check the "remote" first, if a job site doesn't provide this selection then I will check the "contractor"part, because 






-------------------------------------------------------Nik!yO- Independent Designer -Portfolio  |   Twitter  |  Instagram  |  Email

Date: Mon, 14 Mar 2016 09:22:23 -0700

**Comment by lukasz-madon** [comment]
I'm not sure how this is related to this repo.

**Comment by danse** [comment]
@lukasz-madon well, i was thinking that if you like the idea, we can have a different structure for the `Job boards` section in the README. Another idea about that section, is to include platforms like Upwork, Freelancer, etcetera. I think that Guru is actually closer to those than to other sites
