### ISSUE TITLE
remote preferred location

### ISSUE THREAD

**Issue by ruwhan** [lukasz-madon/awesome-remote-job#50]
maybe it is better to also cite the preferred location for the applicant. for example:

- Company Name (Portland)
- Acme Company (UTC -5)
- Foo (Europe)
- Bar (Anywhere)

**Comment by tedder** [comment]
percent of company/team that is remote would be helpful too.

**Comment by lukasz-madon** [comment]
I added that bit to CONTRIBUTING.md, but people that contribute may not know or company policy may change over time - that's why I accept PRs without it.

Having the % of company is useful. I'm trying to accept companies with remote DNA. 

I think I'll solve these problem with Scraper with all jobs.
