### ISSUE TITLE
Can't identify international positions

### ISSUE THREAD

**Issue by achanda** [lukasz-madon/awesome-remote-job#59]
There should be a way to differentiate if a job is remote within a country or remote internationally. I propose globally defining flags for those and adding the flags next to each company name. The other option is to allow only international jobs. Thoughts?

**Comment by lukasz-madon** [comment]
Yes, that's a good thing to know. I added this bit to https://github.com/lukasz-madon/awesome-remote-job/blob/master/CONTRIBUTING.md

The problem is githubers that make PRs may not know what's the location restrictions or it may change, that's why I accept PRs without description. Ideally you would have:

- No location means it's whole world
- region or country restriction e.g. US-only, Europe-only
- time constrains e.g. workday overlaps New York afternoons (1700 - 2200 UTC)

Feel free to make a PRs with it.
