### ISSUE TITLE
Remote companies on careers.stackoverflow.com

### ISSUE THREAD

**Issue by lukasz-madon** [lukasz-madon/awesome-remote-job#70]
This query http://careers.stackoverflow.com/companies?searchTerm=&location=&allowsremote=true

return companies that allows remote working. Should we merge this or add it to list?

**Comment by RichardLitt** [comment]
:+1: for doing it, but how do we ensure that the list is up to date? Do we bother?

**Comment by waldyrious** [comment]
I think remote working policies don't change often enough for keeping the list up-to-date to be a burden. On the other hand, it might be a different thing to "have remote DNA" and simply happen to be, say, temporarily experimenting with remote workers. Besides, if we link to the list rather than include its entries here, we ensure that it will be always up to date with no work on our end. I am not sure what the best approach is, just listing some pros and cons.
